---
services:
  watchtower:
    # image: containrrr/watchtower
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      # Disable rolling restart since it's not recommend
      # - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_DISABLE_CONTAINERS=jackett
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${WATCHTOWER_NOTIFICATION_GOTIFY_URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN}
      # 当 Gotify 没有使用反向代理和 TLS 加密时使用
      # - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
    networks:
        - backend

networks:
  backend:
    external: true
